apiVersion: v1
kind: Pod
metadata:
  name: dns
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: corednstest
    image: 
    volumeMounts:
    - name: shared-data
      mountPath: /coredns/e2e
